NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

print(np.__version__)

1.25.2


# 0-D Arrays
0-D are scalers basically


In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D Arrays

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?

ChatGPT
NumPy Arrays offer the ndim attribute, indicating the array's dimensions.

In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("a =", a.ndim,"-Dimensional")
print("b =", b.ndim,"-Dimensional")
print("c =", c.ndim,"-Dimensional")
print("d =", d.ndim,"-Dimensional")


a = 0 -Dimensional
b = 1 -Dimensional
c = 2 -Dimensional
d = 3 -Dimensional


# Higher Dimensional Arrays
we can also specify dimentions my ourself

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Access Array Elements

In [ ]:
#For 1-D array
arr = np.array([1, 2, 3, 4])

print(arr[0])
#For 2-D array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
#For 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


# NumPy Array Slicing

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
#print(arr[Start:End])

#negative Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
#Slicing 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
#exaple 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])
#example 3
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[2 3 4 5]
[5 6]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# Checking the Data Type of an Array


In [21]:

arr = np.array([1, 2, 3, 4])

print(arr.dtype)
#examle 2
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)
#creating arrray with defined datatype
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)
#Converting Data Type on Existing Arrays
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

int64
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3]
int32


# COPY VS View
The primary distinction between an array copy and a view lies in their ownership and behavior regarding modifications.

A copy creates a new array, retaining ownership of its data. Changes to it won't affect the original array, and vice versa.

In contrast, a view is not a new array; it merely provides a perspective on the original array. As such, changes to the view reflect on the original array, and changes to the original array are reflected in the view.

In [2]:
#copy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
#View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [4]:
#making changes in View

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [5]:
#anothere example
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)
#The copy will returns None.
#The view will returns the original array.

None
[1 2 3 4 5]


# Array Shape

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [7]:
#another example
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

print("Original array:")
print(arr)
print("Shape of the array:", arr.shape)

Original array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Shape of the array: (3, 2, 3)


#Array Reshape
Transform the provided 1-D array, comprising 12 elements, into a 2-D array.

In this transformation, the outermost dimension will consist of 4 arrays, each containing 3 elements.

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Transform the given 1-D array, which consists of 12 elements, into a 3-D array structure.

In this transformation, the outermost dimension will consist of 2 arrays, each containing 3 arrays, and each of these inner arrays will contain 2 elements.

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# NumPy Array Iterating

In [10]:
#Iterate on the elements of the following 1-D array as scaler:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

#Iterate on the elements of the following 2-D array as scaler:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)
#Iterate on the elements of the following 3-D array as scaler:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
1
2
3
4
5
6
1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

In [11]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [12]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [13]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


# Joing

In [14]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Join two 2-D arrays along rows (axis=1):

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

# Using stack Function

In [1]:
#Stacking Along Columns
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
#Stacking along depth
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [5]:
#spliting 2-D
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

# NumPy Searching Arrays

In [6]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


 The searchsorted() method is assumed to be used on sorted arrays

In [7]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


# NumPy Sorting Arrays

In [9]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


This method returns a copy of the array, leaving the original array unchanged.

In [10]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [11]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [12]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy Filter Array

In [13]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [14]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
