NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

print(np.__version__)

1.25.2


# 0-D Arrays
0-D are scalers basically


In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D Arrays

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?

ChatGPT
NumPy Arrays offer the ndim attribute, indicating the array's dimensions.

In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("a =", a.ndim,"-Dimensional")
print("b =", b.ndim,"-Dimensional")
print("c =", c.ndim,"-Dimensional")
print("d =", d.ndim,"-Dimensional")


a = 0 -Dimensional
b = 1 -Dimensional
c = 2 -Dimensional
d = 3 -Dimensional


# Higher Dimensional Arrays
we can also specify dimentions my ourself

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Access Array Elements

In [ ]:
#For 1-D array
arr = np.array([1, 2, 3, 4])

print(arr[0])
#For 2-D array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
#For 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


# NumPy Array Slicing

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
#print(arr[Start:End])

#negative Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
#Slicing 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
#exaple 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])
#example 3
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[2 3 4 5]
[5 6]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# Checking the Data Type of an Array


In [21]:

arr = np.array([1, 2, 3, 4])

print(arr.dtype)
#examle 2
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)
#creating arrray with defined datatype
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)
#Converting Data Type on Existing Arrays
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

int64
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3]
int32
