NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

print(np.__version__)

1.25.2


# 0-D Arrays
0-D are scalers basically


In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D Arrays

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?

ChatGPT
NumPy Arrays offer the ndim attribute, indicating the array's dimensions.

In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("a =", a.ndim,"-Dimensional")
print("b =", b.ndim,"-Dimensional")
print("c =", c.ndim,"-Dimensional")
print("d =", d.ndim,"-Dimensional")


a = 0 -Dimensional
b = 1 -Dimensional
c = 2 -Dimensional
d = 3 -Dimensional


# Higher Dimensional Arrays
we can also specify dimentions my ourself

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
